config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#discover'

  get "/nouscontacter", to: "pages#nouscontacter"
  get "/discover", to: "pages#discover"
  get "/transport", to: "pages#transport"
  get "/alimentation", to: "pages#alimentation"
  get "/agribalyse", to: "pages#redirect_to_agribalyse"
  get "/agribalyse_eng", to: "pages#redirect_to_agribalyse"
  get "/mentions-legales", to: "pages#mentions_legales"
  get "/vieprivee", to: "pages#vieprivee"
  get "/stats", to: "pages#stats"
  get "/impactcarbone", to: "pages#impactcarbone"
  get "/batiment", to: "pages#batiment"



  get "/blog", to: "blog#list"
  # query can be a tag or a category
  get "/blog/:query", to: "blog#list"
  get "/blog/:categorie/:title", to: "blog#article"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/aliment.rb
class Aliment < ApplicationRecord

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
# coding: utf-8
require 'kramdown'

class BlogController < ApplicationController
  def article
    file_path = lookup_context.find_file("#{controller_path}/#{params[:title]}.md").identifier

    # Handle the frontmatter
    parsed = FrontMatterParser::Parser.parse_file(file_path)
    @meta = parsed
    # Convert MD to HTML
    @content = Kramdown::Document.new(parsed.content).to_html
  end

  def list
    all_articles = Dir.glob("#{Rails.root}/app/views/blog/*.md").map do |file_path|
      parsed = FrontMatterParser::Parser.parse_file(file_path)
      parsed.front_matter.merge({'url' => "/blog/#{parsed['catégorie']}/#{file_path.split('/').last}"})
    end

    all_articles.filter! { |a| a['status'] == :published.to_s }

    all_articles = all_articles.sort_by! { |a| Date.parse(a["date"]) }.reverse

    @articles = if !params[:query]
      all_articles
    else
      all_articles.filter do |article|
        article['catégorie'] == params[:query] || article['tags'].include?(params[:query])
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def agribalyse
  end

  def agribalyse_eng
  end

  def redirect_to_agribalyse
    redirect_to "https://agribalyse.fr"
  end

  def courses
  end

  def discover
  end

  def batiment
  end

  def mentions_legales
  end

  def nouscontacter
  end

  def transport
  end

  def alimentation
  end

  def impactcarbone
  end

  def vieprivee
  end

  def stats
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/blog/article.html.erb
<% content_for :meta_title, @meta['titre'] %>
<% content_for :meta_description, "#{DEFAULT_META["meta_product_name"]} - #{@meta['intro']}" %>
<% content_for :meta_image, image_path(@meta['image']) %>

<main role="main" class="container" >
    <div class="col-md-8 blog-main mx-auto">
      <div class="blog-post">
      <header>
        <h1><%= @meta['titre'] %></h1>
        <em>Publié le <%=@meta['date']%> dans <a href="/blog/<%=@meta['catégorie']%>">
        <span class="badge badge-info"><%=@meta['catégorie']%></span></a>
        </em>
        <img alt="<%= @meta['description de l\'image'] %>" width="100%" src="<%= image_path(@meta['image']) %>" />
      </header>
        <%= raw @content %>
      </div><!-- /.blog-post -->
      <p id="article-tags"><% @meta['tags'].each do |tag| %>
        <a href="/blog/<%=tag%>"><span class="badge badge-light"><%= tag %></span></a>
      <% end %></p>

    </div><!-- /.blog-main -->

</main>

app/views/blog/list.html.erb
<div id="blog" class="container">
    <h1>Le blog d'Ecolab</h1>

    <div class="d-flex flex-row align-items-center flex-wrap justify-content-center">
      <%= form_tag blog_path, method: :get, class: "searchbar form-inline search-form-control" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "td form-control",
          placeholder: "Chercher un article de blog par catégorie ou tag"
        %>
      <!--   <i class="fas fa-search"></i> -->
      <% end %>

      <%= link_to "Nouvelle recherche", blog_path, :query => params[:query], class:"btn btn-grey ml-3" %>
    </div>

    <div class="row mb-2" id="articles">


    <% @articles.each do |article| %>
        <div class="col-md-6">
        <div class="article-card row row align-items-center no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">

            <h3><%= article['titre'] %></h3>
            <div class="mb-1 text-muted"><%= article['date'] %> <span class="badge badge-info"><%= article['catégorie'] %></span></div>
            <p class="card-text mb-auto"><%=  article['intro']%></p>
            <a class="stretched-link" href="<%= article['url'] %>">Lire la suite</a>
            <div class="tags"><% article['tags'].each do |tag| %>
                <span class="badge badge-light"><%= tag %></span>
            <% end %></div>
        </div>
        <div class="col-auto d-none d-lg-block p-4">
            <img height="200px" src="<%= image_path(article['image']) %>" />
        </div>
        </div>
        </div>
    <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />


    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon (2).ico'%>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <meta name="google-site-verification" content="nnNsghSNeJJLsrrpFOYyHagBu6aIuJewQK9WalTnA_0" />
  </head>
  <body>

    <%= render 'shared/navbar'  %>
    <%#= render 'shared/flash'  %>
    <div>
      <%= yield %>
    </div>
    <%= render 'shared/footer'  %>



    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <!-- Matomo -->
    <script type="text/javascript">
      var _paq = window._paq || [];
      /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
        var u="//stats.data.gouv.fr/";
        _paq.push(['setTrackerUrl', u+'matomo.php']);
        _paq.push(['setSiteId', '128']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
      })();
    </script>
    <!-- End Matomo Code -->
  </body>
</html>

app/views/pages/alimentation.html.erb
<% content_for :meta_title, "#{DEFAULT_META["meta_product_name"]} - Alimentation - L'impact de nos assiettes sur le climat" %>
<% content_for :meta_description, "Des données ouvertes pour une alimentation moins émettrice en CO2" %>
<% content_for :meta_image, image_path("alimentation/ecolab-alimentation.PNG") %>

<div class="fil-ariane-bar">
  <p id="accueil" class="fil-ariane-texte"><a href="/">Accueil</a></p>
    <i class="fas fa-chevron-right"></i>
  <p class="fil-ariane-texte">Secteur</p>
    <i class="fas fa-chevron-right"></i>
  <p class="fil-ariane-texte"><a href="/alimentation">Se nourrir</a></p>
</div>

<div class="hero" role="banner">
  <div class="hero__container hero__container_landing p-5" style="background: linear-gradient(0deg, white, #FFCF5C);">

    <%#= image_tag("data.svg", {:style => "width:70vh; margin: 10px; height: 70vh;"}) %>
    <img class="images-banner" src="<%= image_path('alimentation/listalim.svg') %>"/>
      <div class="texts-banner">
        <h1 class="banner_title-trans">L'impact de l'alimentation sur le climat</h1>
        <%#= render '/shared/search-bar' %>
        <p class="banner_subtitle">Des données ouvertes pour une alimentation moins émettrice en CO2.</p>

        <div class="place-du-button-et-lien">

          <%#= link_to "Découvrez les données ouvertes", '/agribalyse', class:"how" %>
        </div>

        <div class="how">
          <%#= link_to "Mieux comprendre les enjeux", 'https://ecolab.ademe.fr/blog/transport/impact-carbone-mobilite-eco-deplacement.md', target: "_blank" %>
        </div>
      </div>
    <%#= image_tag("empreinte.svg", {:style => "width:70vh; margin: 10px; height: 70vh;"}) %>
    <img class="images-banner" src="<%= image_path('alimentation/applialim.svg') %>"/>
  </div>
</div>

<section class="section">
  <h2 class="section__title section-margin">Utilisez les données d'impact de +2500 aliments dans vos produits et services</h2>

  <div class="element-text">
    <div class="text-p">
      <strong class="titre-p mb-2">Des données ouvertes, pour tous</strong>
      <p>Disponibles en OpenData, ces données  sont libres, en simple consultation, ou pour être réutilisées dans votre service</p>
      </div>
    <div class="text-p">
      <strong class="titre-p mb-2">Dans les applications préférées des français</strong>
      <p>Ces données sont directement mises à disposition de leurs utilisateurs</p>
    </div>
    <div class="text-p">
      <strong class="titre-p mb-2">Un guide pour les développeurs</strong>
      <p>Format CSV, API, retrouvez toutes les informations techniques sur les méthodes d’intégrations dans notre documentation</p>
    </div>
  </div>

  <div class="place-du-button-et-lien">
    <%= link_to "Découvrez la base Agribalyse", '/agribalyse', class:"btn btn-yellow" %>
    <%#= link_to "Documentation", '/agribalyse', class:"how" %>

    <%#= link_to "Découvrez les données ouvertes", '/agribalyse', class:"how" %>
  </div>
</section>

<!-- <section class="section">
  <div class="reu-container">
    <p class="reu-title">Ils intègrent les données Agribalyse</p>
    <div class="d-flex flex-row flex-wrap justify-content-center">
      <%= link_to "https://yuka.io/", target: "_blank", alt: "Yuka" do %>
        <div>
          <div class="reu-category" style="background-size: contain; background-repeat: no-repeat;background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(<%= image_path('alimentation/reutilisateurs/yuka-logo') %>);">
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
 -->
<ul class="nav nav-pills" id="pills-tab" role="tablist">
  <!-- <li class="nav-item nav-bar">
      <a class="nav-link active step pills-color" id="pills-first-tab" data-toggle="pill" href="#pills-first" role="tab" aria-controls="pills-first" aria-selected="true">Proposition 1 (dummy data)</a>
  </li> -->
  <li class="nav-item nav-bar">
      <a class="nav-link step pills-color" id="pills-second-tab" data-toggle="pill" href="#pills-second" role="tab" aria-controls="pills-second" aria-selected="false">Proposition 1</a>
  </li>
  <!--     <li class="nav-item nav-bar">
      <a class="nav-link step pills-color" id="pills-third-tab" data-toggle="pill" href="#pills-third" role="tab" aria-controls="pills-third" aria-selected="false">Proposition 3</a>
  </li> -->
</ul>

<div class="tab-content" id="pills-tabContent">
  <!--   <div class="tab-pane fade show active" id="pills-first" role="tabpanel" aria-labelledby="pills-first-tab">
      <div class="container align-text-center">
        <h4 class="p-4">Calcule l'impact CO2 de ton alimentation (teste avec "porc", "fraise" et "boeuf" 😬)</h4>
        <p class="mb-4">Intégrez notre module de calcul chez vous, par exemple rendre un article de blog plus intéractif pour le lecteur, simplement en ajoutant cette ligne à votre page Web :</p>
        <code>
          < iframe width="800" height="1200" src="https://food-co2.herokuapp.com/" >< /iframe>
        </code>
        <h6 class="mt-5">Exemple :</h6>
    </div>
  </div> -->

  <div class="tab-pane fade show active" id="pills-second" role="tabpanel" aria-labelledby="pills-second-tab">
    <div class="container align-text-center">
      <h4 class="p-4">Une simple recherche de fruit ou légume et l'app vous informe si le mois en cours est la saison pour celui-ci</h4>
      <p class="mb-4">Intégrez notre module de calcul chez vous, par exemple rendre un article de blog plus intéractif pour le lecteur, simplement en ajoutant cette ligne à votre page Web :</p>
      <code>
        &lt;script
          id="datagir-fruits-et-legumes"
          src="https://mesfruitsetlegumesdesaison.fr/iframe.js"
          data-search="?theme=classic"
        >&lt;/script>
      </code>
      <h6 class="mt-5 mb-3">Exemple :</h6>
      <div id="iframe1">
        <script
          id="datagir-fruits-et-legumes"
          src="https://mesfruitsetlegumesdesaison.fr/iframe.js"
          data-search="?theme=classic"
        ></script>
      </div>

    </div>
  </div>
</div>

<%= render '/shared/newsletter' %>
<%= render '/shared/twitter' %>

app/views/pages/batiment.html.erb
<% content_for :meta_title, "#{DEFAULT_META["meta_product_name"]} - Bâtiment - L'impact de la consommation énergétique des logements" %>
<% content_for :meta_description, "Faciliter par les données, la rénovation et la décarbonation du secteur du bâtiment." %>
<% content_for :meta_image, image_path("Seloger/ecolab-batiment.PNG") %>

<div class="fil-ariane-bar">
  <p id="accueil" class="fil-ariane-texte"><a href="/">Accueil</a></p>
    <i class="fas fa-chevron-right"></i>
  <p class="fil-ariane-texte">Secteur</p>
    <i class="fas fa-chevron-right"></i>
  <p class="fil-ariane-texte"><a href="/batiment">Se loger</a></p>
</div>

<div class="hero" role="banner">
  <div class="hero__container hero__container_landing p-5" style="background: linear-gradient(0deg, white, #FF647C);">
    <%#= image_tag("data.svg", {:style => "width:70vh; margin: 10px; height: 70vh;"}) %>
    <img class="images-banner" id="trotti" src="<%= image_path('Seloger/buildings') %>"/>
    <div class="texts-banner">
      <h1 class="banner_title-trans">L'impact de la consommation énergétique des logements</h1>
      <%#= render '/shared/search-bar' %>
      <p class="banner_subtitle">Faciliter par les données, la rénovation et la décarbonation du secteur du bâtiment.</p>
      <div class="how">
        <%#= link_to "👷   Page encore en construction", '', target: "_blank" %>
      </div>
    </div>
    <img class="images-banner" src="<%= image_path('Seloger/wip') %>"/>
  </div>
</div>

<!-- Section integrer le simulateur -->
<div class="d-flex flex-column">
  <div class="section-bat section-droite section-demandeur d-flex flex-column align-items-center justify-content-center pt-5 pb-5">
    <div class="text-p d-flex flex-column align-items-center justofy-content-end">
      <h4>Exemple de cas d'usage de la donnée : les diagnostics de performance énergétique (DPE) pour les logements</h4>
      <p>Utilisez ces données pour apporter de nouvelles informations à vos utilisateurs !
      </p>
      <p>A noter : les données du DPE réalisé ne reflètent pas nécessairement la qualité énergétique du bien actuellement. Entre la date de réalisation du DPE et aujourd’hui, des travaux d’amélioration ont pu être réalisés.
      </p>
      <%= link_to "Voir toutes les données sur data.ademe.fr", 'https://data.ademe.fr/reuses/diagnostics-de-performance-energetique-pour-les-logements-par-habitation', target: "_blank", class:"btn btn-grey mt-3" %>
    </div>
    <iframe src="https://koumoul.com/s/data-fair/app/relation-entre-classes-energetiques-et-ges-2?embed=true" width="100%" height="500px" style="background-color: transparent; border: none;"></iframe>
  </div>
</div>

<%= render '/shared/newsletter' %>
<%= render '/shared/twitter' %>

app/views/pages/mentions_legales.html.erb
<h1>Mentions Légales</h1>

<div class="container">
  <div class="card">
    <div class="card-body">
      <div>
        <h2>Informations légales</h2>
        <p>Ecolab est un service créé par l'<a href="https://www.ademe.fr" alt="ADEME">ADEME</a> en partenariat avec <a href="https://beta.gouv.fr/" alt="Beta.gouv.fr">Beta.gouv.fr</a>.</p>
        <p>
          Siège social de l'ADEME :<br/>
          20, avenue du Grésillé<br/>
          BP 90406<br/>
          49004 Angers Cedex 01<br/>
          Tél. : 02 41 20 41 20<br/>
        </p>
      </div>

      <div>
        <h2>Directeur de publication</h2>
        <p>Martin Régner - ADEME</p>
      </div>

      <div>
        <h2>Prestataire d'hébergement</h2>
        <p>
          Heroku, Inc<br/>
          321 11th Street San Francisco,<br/>
          CA - Etats-Unis
        </p>
        <p>Les données sont hébergées en Europe.</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/nouscontacter.html.erb
<div class="fil-ariane-bar">
  <p id="accueil" class="fil-ariane-texte"><a href="/">Accueil</a></p>
    <i class="fas fa-chevron-right"></i>
  <p class="fil-ariane-texte">Secteur</p>
    <i class="fas fa-chevron-right"></i>
  <p class="fil-ariane-texte"><a href="/nouscontacter">nous contacter</a></p>
</div>










<%= render '/shared/pageenconstruction' %>



<!-- <div class="container-wip">

  <div class="wip-content">
    <div class="work-in-progress">
      <h1 class="titre-wip">Vous souhaitez suivre les évolutions d’Ecolab ?</h1>
      <p class="para-wip">Laissez-nous ici votre contact et rejoignez notre communauté.</p>
      <img class="illustration-wip" src="<%#= image_path('contact.png') %>"/>
    </div>

    <div class="contact-form mt-5">
      <%#= text_field_tag :name, params[:name], class: "td form-control w-80", placeholder: "Votre nom", label: "Votre Nom"%>
      <%#= text_field_tag :email, params[:email], class: "td form-control w-80", placeholder: "Votre email"%>
      <%#= text_field_tag :message, params[:message], placeholder: "Ecrivez ici votre message", class: "td form-control w-80 h-80"%>
      <button class="btn-flat-download-index">
        <%#= link_to "Envoyer" %>
      </button>
    </div>

  </div>

</div> -->

app/views/pages/vieprivee.html.erb
<div class="container p-5">
<h1 class="pb-3">Vie privée 🙈</h1>
<h6>Nous recueillons des statistiques anonymes sur l'utilisation du site, que nous utilisons dans le seul but d'améliorer le service, conformément aux <span><a href="https://www.cnil.fr/fr/solutions-pour-les-cookies-de-mesure-daudience">recommandations de la CNIL</a></span> et au règlement RGPD. Ce sont les seules données qui quittent votre navigateur.

<br>
<br>

Vous pouvez vous soustraire de cette mesure d'utilisation du site ci-dessous.</h6>


<iframe style="border: 0;
        height: 200px;
        width: 100%;
        font-family: sans-serif;"
        src="https://stats.data.gouv.fr/index.php?module=CoreAdminHome&action=optOut">
</iframe>

</div>

app/views/shared/_flash.html.erb
<div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong>Le Saviez-vous ?</strong> 🎉 eh bien non vous ne saviez pas.</span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

app/views/shared/_footer.html.erb
<footer class="footer" role="contentinfo">
    <div class="container p-4">
      <div class="footer__logo">
        <!-- <img src= <%#= image_path('ademe-logo.jpg') %>> -->
          <%= link_to "https://www.ademe.fr/", target: "_blank" do %>
              <div>
                <img src="<%= image_path('logos/Republique_Francaise_RVB.png') %>"/>
              </div>
              <div>
                  <img src="<%= image_path('logos/ademe-logo.jpg') %>"/>
          <% end %>
        </div>
        <!-- <div class="footer-reseaux">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div> -->
      </div>

        <ul class="footer__links">
          <li><h2>Ecolab</h2></li>
          <li><a href="https://ecolab.ademe.fr/blog/g%C3%A9n%C3%A9ral/pourquoi-ecolab.md">Qui sommes-nous ?</a></li>
          <li><a href="https://beta.gouv.fr/apropos/">Les start-ups d’état</a></li>
          <li><%= link_to "Mentions légales", mentions_legales_path %></li>
          <li><%= link_to "Vie privée", vieprivee_path, target:"_blank" %></li>
          <li><%= link_to "Stats", stats_path, target:"_blank" %></li>
        </ul>


        <ul class="footer__links">
          <li><h2>Nous aider</h2></li>
          <li><a href="https://github.com/betagouv/Ecolab">Contribuer sur Github</a></li>
          <li><a href="https://github.com/JenniferStephan/Ecolab">Envoyer une suggestion</a></li>
          <li><a href="mailto:contact@ecolab.beta.gouv.fr">Contactez-nous !</a></li>
        </ul>

        <ul class="footer__links">
          <li><h2>En collaboration avec</h2></li>
          <li><a href="https://www.ademe.fr/">ADEME</a></li>
          <li><a href="https://beta.gouv.fr/apropos/">Beta.gouv.fr</a></li>
          <li><a href="https://data.ademe.fr/">Data.ademe.fr</a></li>
        </ul>

    </div>
  </footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-ecolab">

  <%= link_to root_path do %>
    <img class="logo" src="<%= image_path('logo_basdecasse.png') %>"/>
  <% end %>



  <!-- <li class="dropdown align-self-center d-none d-sm-block mr-3">
        <button class="dropdown-toggle border-none donnees" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Données
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

          <%#= link_to "Alimentation", alimentation_path, class: "dropdown-item" %>
          <%#= link_to "Bâtiment",batiment_path, class: "dropdown-item" %>
        </div>
  </li> -->

    <ul class="navbar-nav mr-auto">
      <!-- <button class="border-none " type="button" >
          <%#= link_to "Etudes de cas", batiment_path %>
      </button> -->
      <div class="dropdown show">
        <a class="btn btn-secondary dropdown-toggle"  role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
          Secteur
        </a>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item" id="dropdown-item-senourrir" href="/alimentation">🍽 Se nourrir</a>
          <a class="dropdown-item" id="dropdown-item-climat" href="/impactcarbone">🌏 Impact carbone</a>
          <a class="dropdown-item" id="dropdown-item-sedeplacer" href="/transport">🚴🏻 Se déplacer</a>
          <a class="dropdown-item" id="dropdown-item-seloger" href="/batiment">🏡 Se loger</a>
        </div>
      </div>


      <button class="border-none " type="button" >
          <%= link_to "Documentation", "https://datagir.gitbook.io/documentation/", target: "_blank" %>
      </button>
      <button class="border-none " type="button" >
          <%= link_to "Blog", "/blog" %>
      </button>
      <button class="border-none " type="button" >
          <%= link_to "Pourquoi Ecolab ?", "/blog/général/pourquoi-ecolab.md" %>
      </button>

       <button class="border-none " type="button" >
          <%= link_to "S'inscrire à la newsletter", nouscontacter_path %>
      </button>

      <!-- <button class="border-none add-meal" type="button" >
          <%#= link_to "Simuler ma liste de courses", courses_path %>
      </button> -->

    </ul>
  </div>
</div>

app/views/shared/_twitter.html.erb
<section class="section-rs">
  <div class="twitter-flex d-flex flex-row align-items-center justify-content-around">
    <div class="d-flex flex-column mb-2 align-items-center">
      <h4 class="titre-news w-60">Suivez-nous et échangez avec l'équipe également sur Twitter</h4>
      <img class="image-rs" src="<%= image_path('transport/tweet') %>"/>
    </div>
    <a class="twitter-timeline" data-width="400" data-height="350" data-theme="dark" href="https://twitter.com/Ecolab_betagouv?ref_src=twsrc%5Etfw">Les tweets d'Ecolab_betagouv</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
</section>